# Step 1
Load two files, observe the data, and merge them based on the common column(s).
Perform data cleaning on genres feature first. How many unique genres are there in the
dataset? List top 3 genres by count, provide the genre type and count value.

## 1.1: Load Data

In [ ]:
import pandas as pandas
import ast
from collections import Counter

In [ ]:
MOVIE_PATH = '../data/tmdb_5000_movies.csv'
CREDIT_PATH = '../data/tmdb_5000_credits.csv'

In [ ]:
movies = pandas.read_csv(MOVIE_PATH)
credits = pandas.read_csv(CREDIT_PATH)

In [ ]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [ ]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
print("Movies shape: ", movies.shape)
print("Credits shape: ", credits.shape)

Movies shape:  (4803, 20)
Credits shape:  (4803, 4)

In [ ]:
print("Movie Columns: ", movies.columns)
print("Credit Columns: ", credits.columns)

Movie Columns:  Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')
Credit Columns:  Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [ ]:
merged_movie_df = movies.merge(
    credits,
    left_on='id',
    right_on='movie_id',
    suffixes=('_movie', '_credit')
)

In [ ]:
merged_movie_df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_movie', 'vote_average',
       'vote_count', 'movie_id', 'title_credit', 'cast', 'crew'],
      dtype='str')

In [ ]:
merged_movie_df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_movie,vote_average,vote_count,movie_id,title_credit,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
print("Merged shape: ", merged_movie_df.shape)

Merged shape:  (4803, 24)

## 1.2: Clean on Genres feature

In [ ]:
def clean_genres(genres):
    try:
        values = ast.literal_eval(genres)
        return [v['name'] for v in values]
    except:
        return []

merged_movie_df['genres_cleaned'] = merged_movie_df['genres'].apply(clean_genres)

merged_movie_df[['title_movie', 'genres', 'genres_cleaned']].head()

,title_movie,genres,genres_cleaned
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[Adventure, Fantasy, Action]"
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Action, Adventure, Crime]"
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[Action, Crime, Drama, Thriller]"
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Action, Adventure, Science Fiction]"

## Step 1.3 Count unique genres and list top 3 genres by count

In [ ]:
genre_counts = Counter()
for genres in merged_movie_df['genres_cleaned']:
    genre_counts.update(genres)

print("Unique genres: ", len(genre_counts))
print("Top 3 genres: ", genre_counts.most_common(3))

Unique genres:  20
Top 3 genres:  [('Drama', 2297), ('Comedy', 1722), ('Thriller', 1274)]

# Step 2
Now look into the cast feature. Clean the column and find out how many unique
casts in the dataset. List top 3 casts by count, provide the cast’s name and their count value.

## Step 2.1: Clean on Cast

In [15]:
def clean_cast(cast):
    try:
        values = ast.literal_eval(cast)
        return [v['name'] for v in values]
    except:
        return []
    
# Clean the cast column
merged_movie_df["cast_cleaned"] = merged_movie_df["cast"].apply(clean_cast)

# Check the cleaned result
merged_movie_df[["title_movie", "cast", "cast_cleaned"]].head()

,title_movie,cast,cast_cleaned
0,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[Sam Worthington, Zoe Saldana, Sigourney Weave..."
1,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[Johnny Depp, Orlando Bloom, Keira Knightley, ..."
2,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R..."
3,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[Christian Bale, Michael Caine, Gary Oldman, A..."
4,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[Taylor Kitsch, Lynn Collins, Samantha Morton,..."

## Step 2.2: Count unique casts and list top 3 casts by count

In [16]:
cast_counts = Counter()
for casts in merged_movie_df['cast_cleaned']:
    cast_counts.update(casts)

print("Unique casts: ", len(cast_counts))
print("Top 3 casts: ", cast_counts.most_common(3))

Unique casts:  54201
Top 3 casts:  [('Samuel L. Jackson', 67), ('Robert De Niro', 57), ('Bruce Willis', 51)]

# Step 3
Clean keywords feature, answer how many unique keywords in total? List top 3 keywords and their count.

## 3.1: Clean on Keywords

In [18]:
def clean_keyword(keyword):
    try:
        values = ast.literal_eval(keyword)
        return [v['name'] for v in values]
    except:
        return []

merged_movie_df["keywords_cleaned"] = merged_movie_df["keywords"].apply(clean_keyword)
merged_movie_df[["title_movie", "keywords", "keywords_cleaned"]].head()

,title_movie,keywords,keywords_cleaned
0,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[culture clash, future, space war, space colon..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[ocean, drug abuse, exotic island, east india ..."
2,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[spy, based on novel, secret agent, sequel, mi..."
3,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[dc comics, crime fighter, terrorist, secret i..."
4,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[based on novel, mars, medallion, space travel..."

## 3.2: Count unique keywords and list top 3 keywords by count

In [19]:
keyword_counts = Counter()
for keywords in merged_movie_df['keywords_cleaned']:
    keyword_counts.update(keywords)

print("Unique keywords: ", len(keyword_counts))
print("Top 3 keywords: ", keyword_counts.most_common(3))

Unique keywords:  9813
Top 3 keywords:  [('woman director', 324), ('independent film', 318), ('duringcreditsstinger', 307)]

## 4: Create Director column for each Movie

In [ ]:
def get_director(obj):
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            return i['name']
    return np.nan

df['director'] = df['crew'].apply(get_director)

In [ ]:
# Top ranked director by count
top_director = df['director'].value_counts().idxmax()
print(f"\nTop ranked director: {top_director}")

## 5: Vectorization and Distance

In [ ]:
# Vectorize features
def get_vector(item_list, full_vocab):
    return [1 if word in item_list else 0 for word in full_vocab]

# Create vocabularies
genre_vocab = list(unique_genres)
cast_vocab = list(cast_counts.index)
kw_vocab = list(set(all_keywords))
dir_vocab = list(df['director'].dropna().unique())

In [ ]:
# Calculate distance between two movies
def calculate_total_distance(id1, id2):
    row1 = df[df['id'] == id1].iloc[0]
    row2 = df[df['id'] == id2].iloc[0]
    
    # Generate vectors
    g1, g2 = get_vector(row1['genres'], genre_vocab), get_vector(row2['genres'], genre_vocab)
    c1, c2 = get_vector(row1['cast'], cast_vocab), get_vector(row2['cast'], cast_vocab)
    k1, k2 = get_vector(row1['keywords'], kw_vocab), get_vector(row2['keywords'], kw_vocab)
    d1, d2 = get_vector([row1['director']], dir_vocab), get_vector([row2['director']], dir_vocab)
    
    # Calculate Sum of Cosine Distances
    dist = (distance.cosine(g1, g2) + distance.cosine(c1, c2) + 
            distance.cosine(k1, k2) + distance.cosine(d1, d2))
    return round(dist, 3)

In [ ]:
dist_sample = calculate_total_distance(285, 49026)
print(f"\nDistance between 285 and 49026: {dist_sample}")

## 6: Find Top 8 Neighbors

In [ ]:
def get_neighbors(movie_id, k=8):
    distances = []
    for idx, row in df.iterrows():
        if row['id'] == movie_id: continue
        d = calculate_total_distance(movie_id, row['id'])
        if d > 0:
            distances.append((row['id'], d))
    
    # Sort by distance (ascending)
    distances.sort(key=lambda x: x[1])
    return distances[:k]

In [ ]:
print(f"\nTop 8 neighbors for 285:\n", get_neighbors(285))

## 7: Predict Rating

In [ ]:
def predict_rating(title, k=10):
    # Find movie id based on title
    movie_row = df[df['title'] == title].iloc[0]
    m_id = movie_row['id']
    actual = movie_row['vote_average']
    
    # Get top k neighbors
    neighbors = get_neighbors(m_id, k=k)
    neighbor_ids = [n[0] for n in neighbors]
    
    # Average vote_average of top k movies as predicted rating
    neighbor_ratings = df[(df['id'].isin(neighbor_ids)) & (df['vote_average'] > 0)]['vote_average']
    prediction = neighbor_ratings.mean()
    
    return prediction, actual

In [ ]:
pred, actual = predict_rating("Pirates of the Caribbean: At World's End")
print(f"\nPredicted: {pred:.2f}, Actual: {actual}")