# Step 1
Load two files, observe the data, and merge them based on the common column(s).
Perform data cleaning on genres feature first. How many unique genres are there in the
dataset? List top 3 genres by count, provide the genre type and count value.

## 1.1: Load Data

In [3]:
import pandas as pandas

In [6]:
MOVIE_PATH = '../data/tmdb_5000_movies.csv'
CREDIT_PATH = '../data/tmdb_5000_credits.csv'

In [7]:
movies = pandas.read_csv(MOVIE_PATH)
credits = pandas.read_csv(CREDIT_PATH)

In [9]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [10]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [11]:
print("Movies shape: ", movies.shape)
print("Credits shape: ", credits.shape)

Movies shape:  (4803, 20)
Credits shape:  (4803, 4)

In [12]:
print("Movie Columns: ", movies.columns)
print("Credit Columns: ", credits.columns)

Movie Columns:  Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')
Credit Columns:  Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [13]:
merged_movie_df = movies.merge(
    credits,
    left_on='id',
    right_on='movie_id',
    suffixes=('_movie', '_credit')
)

In [15]:
merged_movie_df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_movie,vote_average,vote_count,movie_id,title_credit,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
print("Merged shape: ", merged_movie_df.shape)

Merged shape:  (4803, 24)

## 1.2: CLean on Genres feature