# Step 1
Load two files, observe the data, and merge them based on the common column(s).
Perform data cleaning on genres feature first. How many unique genres are there in the
dataset? List top 3 genres by count, provide the genre type and count value.

## 1.1: Load Data

In [10]:
import pandas as pandas
import ast
from collections import Counter

In [2]:
MOVIE_PATH = '../data/tmdb_5000_movies.csv'
CREDIT_PATH = '../data/tmdb_5000_credits.csv'

In [3]:
movies = pandas.read_csv(MOVIE_PATH)
credits = pandas.read_csv(CREDIT_PATH)

In [4]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
print("Movies shape: ", movies.shape)
print("Credits shape: ", credits.shape)

Movies shape:  (4803, 20)
Credits shape:  (4803, 4)

In [7]:
print("Movie Columns: ", movies.columns)
print("Credit Columns: ", credits.columns)

Movie Columns:  Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')
Credit Columns:  Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [8]:
merged_movie_df = movies.merge(
    credits,
    left_on='id',
    right_on='movie_id',
    suffixes=('_movie', '_credit')
)

In [9]:
merged_movie_df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_movie', 'vote_average',
       'vote_count', 'movie_id', 'title_credit', 'cast', 'crew'],
      dtype='str')

In [15]:
merged_movie_df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_movie,vote_average,vote_count,movie_id,title_credit,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
print("Merged shape: ", merged_movie_df.shape)

Merged shape:  (4803, 24)

## 1.2: Clean on Genres feature

In [12]:
def clean_genres(genres):
    try:
        values = ast.literal_eval(genres)
        return [v['name'] for v in values]
    except:
        return []

merged_movie_df['genres_cleaned'] = merged_movie_df['genres'].apply(clean_genres)

merged_movie_df[['title_movie', 'genres', 'genres_cleaned']].head()

,title_movie,genres,genres_cleaned
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[Adventure, Fantasy, Action]"
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Action, Adventure, Crime]"
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[Action, Crime, Drama, Thriller]"
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[Action, Adventure, Science Fiction]"

## Step 1.3 Count unique genres and list top 3 genres by count

In [ ]:
genre_counts = Counter()
for genres in merged_movie_df['genres_cleaned']:
    genre_counts.update(genres)

print("Unique genres: ", len(genre_counts))
print("Top 3 genres: ", genre_counts.most_common(3))

Unique genres:  20
Top 3 genres:  [('Drama', 2297), ('Comedy', 1722), ('Thriller', 1274)]

# Step 2
Now look into the cast feature. Clean the column and find out how many unique
casts in the dataset. List top 3 casts by count, provide the cast’s name and their count value.

## Step 2.1: Clean on Cast

In [15]:
def clean_cast(cast):
    try:
        values = ast.literal_eval(cast)
        return [v['name'] for v in values]
    except:
        return []
    
# Clean the cast column
merged_movie_df["cast_cleaned"] = merged_movie_df["cast"].apply(clean_cast)

# Check the cleaned result
merged_movie_df[["title_movie", "cast", "cast_cleaned"]].head()

,title_movie,cast,cast_cleaned
0,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[Sam Worthington, Zoe Saldana, Sigourney Weave..."
1,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[Johnny Depp, Orlando Bloom, Keira Knightley, ..."
2,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R..."
3,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[Christian Bale, Michael Caine, Gary Oldman, A..."
4,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[Taylor Kitsch, Lynn Collins, Samantha Morton,..."

## 2.2: Count unique casts and list top 3 casts by count

In [16]:
cast_counts = Counter()
for casts in merged_movie_df['cast_cleaned']:
    cast_counts.update(casts)

print("Unique casts: ", len(cast_counts))
print("Top 3 casts: ", cast_counts.most_common(3))

Unique casts:  54201
Top 3 casts:  [('Samuel L. Jackson', 67), ('Robert De Niro', 57), ('Bruce Willis', 51)]